# generated by datamodel-codegen:
#   filename:  datatypes/Line.json

from __future__ import annotations

from typing import Literal

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field, RootModel

from .Point import Point


class RegionType(RootModel[Literal["line"]]):
    root: Literal["line"] = Field(
        "line", description="Type of region", title="Region type"
    )


class Line(BaseModel):
    """
    A straight line marked on an image or in absolute plate space.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    region_type: Literal["line"] = Field(
        "line", alias="regionType", description="Type of region", title="Region type"
    )
    points: list[Point] = Field(..., max_length=2, min_length=2)
