# generated by datamodel-codegen:
#   filename:  datatypes/PointCloud.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from .ScannedPoint import ScannedPoint as ScannedPoint_1


class PointCloud(BaseModel):
    """
    A cloud (list) of scanned points
    """

    points: list[ScannedPoint_1] = Field(
        ..., description="List of points making up the PointCloud", title="Points list"
    )
