# generated by datamodel-codegen:
#   filename:  datatypes/Polygon.json

from __future__ import annotations

from typing import Annotated, Literal

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import ConfigDict, Field, RootModel

from .Point import Point


class RegionType(RootModel[Literal["polygon"]]):
    root: Annotated[
        Literal["polygon"], Field(description="Type of region", title="Region type")
    ] = "polygon"


class Polygon(BaseModel):
    """
    <A polygonal region marked on an image or in absolute plate space.The polygon is defined by at least three points, and is assumed to be closed by a line from the last point to the first. The path should not cross itself, including on the closing segment.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    region_type: Annotated[
        Literal["polygon"],
        Field(alias="regionType", description="Type of region", title="Region type"),
    ] = "polygon"
    points: Annotated[list[Point], Field(min_length=3)]
