# generated by datamodel-codegen:
#   filename:  datatypes/ResolutionCutoffs.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field, NonNegativeFloat, confloat


class ResolutionCutoffs(BaseModel):
    """
    Resolution cutoff criteria
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    r_merge: NonNegativeFloat | None = Field(
        None, alias="R_merge", description="R merge", title="R(merge)"
    )
    r_meas: NonNegativeFloat | None = Field(
        None, alias="R_meas", description="R meas", title="R_meas"
    )
    r_pim: NonNegativeFloat | None = Field(
        None, alias="R_pim", description="R pim", title="R_pim"
    )
    i_over_sig_i: float | None = Field(
        None, alias="I_over_SigI", description="Average I / sigma(I)", title="I/SigI"
    )
    cc_one_half: confloat(ge=-1.0, le=-1.0) | None = Field(
        None, alias="CC_one_half", description="CC 1/2", title="CC(1/2)"
    )
    cc_ano: confloat(ge=-1.0, le=-1.0) | None = Field(
        None, alias="CC_ano", description="CC_ano", title="CC_ano"
    )
    sig_ano: float | None = Field(
        None, alias="SigAno", description="SigAno", title="SigAno"
    )
