# generated by datamodel-codegen:
#   filename:  datatypes/ResolutionCutoffs.json

from __future__ import annotations

from typing import Annotated

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import ConfigDict, Field, NonNegativeFloat


class ResolutionCutoffs(BaseModel):
    """
    Resolution cutoff criteria
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    r_merge: Annotated[
        NonNegativeFloat | None,
        Field(alias="R_merge", description="R merge", ge=0, title="R(merge)"),
    ] = None
    r_meas: Annotated[
        NonNegativeFloat | None,
        Field(alias="R_meas", description="R meas", ge=0, title="R_meas"),
    ] = None
    r_pim: Annotated[
        NonNegativeFloat | None,
        Field(alias="R_pim", description="R pim", ge=0, title="R_pim"),
    ] = None
    i_over_sig_i: Annotated[
        float | None,
        Field(alias="I_over_SigI", description="Average I / sigma(I)", title="I/SigI"),
    ] = None
    cc_one_half: Annotated[
        float | None,
        Field(
            alias="CC_one_half", description="CC 1/2", ge=-1.0, le=-1.0, title="CC(1/2)"
        ),
    ] = None
    cc_ano: Annotated[
        float | None,
        Field(alias="CC_ano", description="CC_ano", ge=-1.0, le=-1.0, title="CC_ano"),
    ] = None
    sig_ano: Annotated[
        float | None, Field(alias="SigAno", description="SigAno", title="SigAno")
    ] = None
