# generated by datamodel-codegen:
#   filename:  datatypes/SampleStub.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import ConfigDict, Field, RootModel


class MxlimsBaseType(RootModel[Literal["Sample"]]):
    root: Annotated[
        Literal["Sample"],
        Field(
            description="The type of the MXLIMS core object referred to",
            title="MxlimsBaseType",
        ),
    ] = "Sample"


class SampleStub(BaseModel):
    """
    Uuid container, used for Uuid-only links to Samples in messages
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mxlims_base_type: Annotated[
        Literal["Sample"],
        Field(
            alias="mxlimsBaseType",
            description="The type of the MXLIMS core object referred to",
            title="MxlimsBaseType",
        ),
    ] = "Sample"
    uuid: Annotated[
        UUID,
        Field(
            description="Permanent unique identifier string of object referred to",
            pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
            title="Uuid",
        ),
    ]
