# generated by datamodel-codegen:
#   filename:  datatypes/ScannedPoint.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, PositiveFloat, PositiveInt


class ScannedPoint(BaseModel):
    """
    Scanned point in sample, given in goniostat coordinate system at omega==kappa==phi==0
    """

    coordinates: list[float] = Field(
        ..., title="Point coordinates (sampX, sampY, sampZ)"
    )
    intensity: float | None = Field(
        None,
        description="Measured intensity at point, in arbitrary units",
        title="Intensity",
    )
    resolution: PositiveFloat | None = Field(
        None, description="Resolution observed at the scanned point", title="Resolution"
    )
    spot_count: PositiveInt | None = Field(
        None,
        alias="spotCount",
        description="Number of spots observed at the scanned point",
        title="Spot count",
    )
