# generated by datamodel-codegen:
#   filename:  datatypes/Tensor.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field


class Tensor(BaseModel):
    """
    Tensor
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    eigenvalues: list[float] = Field(
        ...,
        description="Eigenvalues of tensor",
        max_length=3,
        min_length=3,
        title="Eigenvalues",
    )
    eigenvectors: list[list[float]] = Field(
        ...,
        description="Eigenvectors (3D unit vectors) of tensor, in same order as eigenvalues",
        max_length=3,
        min_length=3,
        title="Eigenvectors",
    )
