# generated by datamodel-codegen:
#   filename:  datatypes/UnitCell.json

from __future__ import annotations

from typing import Annotated

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import ConfigDict, Field, PositiveFloat


class UnitCell(BaseModel):
    """
    Crystallographic unit cell,

    matches mmCIF items cell.length_{a,b,c} and cell.angle_{alpha,beta,gamma} in category
    cell (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/cell.html)
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    a: Annotated[PositiveFloat, Field(description="A axis length (A)", gt=0, title="A")]
    b: Annotated[PositiveFloat, Field(description="B axis length (A)", gt=0, title="B")]
    c: Annotated[PositiveFloat, Field(description="C axis length (A)", gt=0, title="C")]
    alpha: Annotated[
        PositiveFloat, Field(description="alpha angle (degree)", gt=0, title="Alpha")
    ]
    beta: Annotated[
        PositiveFloat, Field(description="beta angle (degree)", gt=0, title="Beta")
    ]
    gamma: Annotated[
        PositiveFloat, Field(description="gamma angle (degree)", gt=0, title="Gamma")
    ]
