# generated by datamodel-codegen:
#   filename:  objects/CollectionSweep.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from ..rawobjects.RawCollectionSweep import RawCollectionSweep


class CollectionSweep(RawCollectionSweep):
    """
    Crystallographic sweep data set, with typed JSON containment lists
    """

    derived_data_sets: Optional[List[CollectionSweep]] = Field(
        None, alias="derivedDataSets"
    )


CollectionSweep.model_rebuild()
