# generated by datamodel-codegen:
#   filename:  objects/CrystallographicSample.json

from __future__ import annotations

from ..data.CrystallographicSampleData import CrystallographicSampleData
from .PreparedSample import PreparedSample


class CrystallographicSample(CrystallographicSampleData, PreparedSample):
    """
    Crystallographic Sample, with typed JSON containment lists
    """
