# generated by datamodel-codegen:
#   filename:  objects/Crystal.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Optional, Union

from ..rawobjects.RawCrystal import RawCrystal
from . import MxExperiment, MxProcessing


class Crystal(RawCrystal):
    """
    Crystal or location for measuring diffraction, with typed JSON containment lists. Note that crystals are optional and are generally used ONLY where a region, loop, or other LogisticalSample is found to have several crystals during the actual experiment.
    """

    jobs: Optional[List[Union[MxExperiment, MxProcessing]]] = None
