# generated by datamodel-codegen:
#   filename:  objects/DewarShipment.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from ..rawobjects.RawShipment import RawShipment
from . import Dewar


class DewarShipment(RawShipment):
    """
    Shipment of Dewars, with typed JSON containment lists
    """

    contents: Optional[List[Dewar]] = Field(None, min_length=1)
