# generated by mxlims/scripts
#  filename Dewar.py

from __future__ import annotations
from typing import Optional, Union
from ..core.LogisticalSample import LogisticalSample
from ..data.LogisticalSampleData import LogisticalSampleData
from ..data.DewarData import DewarData
from .Puck import Puck
from .Shipment import Shipment

class Dewar(DewarData, LogisticalSampleData, LogisticalSample):
    """MXLIMS pydantic model class for Dewar
    """
    
    @property
    def container(self) -> Optional[Shipment]:
        """getter for Dewar.container"""
        return self.objects_by_id["LogisticalSample"].get(self.container_id)
    
    @container.setter
    def container(self, value: Optional[Shipment]):
        """setter for Dewar.container"""
        if value:
            if not isinstance(value, Shipment):
                raise ValueError(
                    "container must be of type Shipment"
                )
            self.container_id = value.uuid
        else:
            self.container_id = None

    @property
    def contents(self) -> list[Puck]:
        """getter for Dewar.contents list"""
        uid = self.uuid
        result = []
        for obj in self.objects_by_id["LogisticalSample"]:
            if uid == obj.container_id:
                result.append(obj)
        return result
    