# generated by datamodel-codegen:
#   filename:  objects/DropRegion.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import Field

from ..rawobjects.RawDropRegion import RawDropRegion
from .Crystal import Crystal
from .MxExperiment import MxExperiment
from .MxProcessing import MxProcessing


class DropRegion(RawDropRegion):
    """
    A region in a well drop where crystals may be found, with typed JSON containment lists
    """

    contents: Optional[List[Crystal]] = Field(None, min_length=1)
    jobs: Optional[List[Union[MxExperiment, MxProcessing]]] = None
