# generated by datamodel-codegen:
#   filename:  objects/DropRegion.json

from __future__ import annotations

from typing import Optional

from pydantic import Field

from ..data.DropRegionData import DropRegionData
from ..references.CrystallographicSampleRef import CrystallographicSampleRef
from ..references.WellDropRef import WellDropRef
from .LogisticalSample import LogisticalSample


class DropRegion(DropRegionData, LogisticalSample):
    """
    A region in a well drop where crystals may be found, with typed JSON containment lists
    """

    sample_ref: Optional[CrystallographicSampleRef] = Field(None, alias="sampleRef")
    container_ref: Optional[WellDropRef] = Field(None, alias="containerRef")
