# generated by datamodel-codegen:
#   filename:  objects/Job.json

from __future__ import annotations

from typing import List, Optional

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field

from ..references.MxlimsRef import MxlimsRef


class Job(BaseModel):
    """
    Base class for MXLIMS Jobs - an experiment or calculation producing Datasets
    """

    sample_ref: Optional[MxlimsRef] = Field(None, alias="sampleRef")
    started_from_ref: Optional[MxlimsRef] = Field(None, alias="startedFromRef")
    logistical_sample_ref: Optional[MxlimsRef] = Field(
        None, alias="logisticalSampleRef"
    )
    reference_data_refs: Optional[List[MxlimsRef]] = Field(
        None, alias="referenceDataRefs"
    )
    template_data_refs: Optional[List[MxlimsRef]] = Field(
        None, alias="templateDataRefs"
    )
    input_data_refs: Optional[List[MxlimsRef]] = Field(None, alias="inputDataRefs")
