# generated by mxlims/impl/generate_code.py
#  filename Macromolecule.py

# NB UUID has to be imported to avoid pydantic errors ??
from __future__ import annotations
from pydantic import Field
from typing import Any, Literal, Optional, Union, TYPE_CHECKING
# from uuid import UUID, uuid1
from ..objects.Sample import Sample
from ..data.MacromoleculeData import MacromoleculeData
if TYPE_CHECKING:
    from .MacromoleculeSample import MacromoleculeSample

class Macromolecule(MacromoleculeData, Sample):
    """MXLIMS pydantic model class for Macromolecule
    """
    def __init__(self, **data: Any) -> None:
        super().__init__(**data)
        Sample.__init__(self, **data)
        
    mxlims_type: Literal["Macromolecule"] = Field(
        "Macromolecule",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
        frozen=True,
    )
    
    @property
    def main_samples(self) -> list[MacromoleculeSample]:
        """getter for Macromolecule.main_samples list"""
        return self._get_link_1n("Sample", "main_component_id")

    @main_samples.setter
    def main_samples(self, values: list[MacromoleculeSample]):
        """setter for Macromolecule.main_samples list"""
        from .MacromoleculeSample import MacromoleculeSample

        for obj in values:
            if not isinstance(obj, MacromoleculeSample):
                raise ValueError("%s is not of type MacromoleculeSample" % obj)
        self._set_link_1n_rev("Sample", "main_component_id", values)
