# generated by mxlims/impl/generate_code.py
#  filename Macromolecule.py

from __future__ import annotations
from pydantic import Field
from typing import Any, Literal, Optional, Union, TYPE_CHECKING
from ..objects.Sample import Sample
from ..data.MacromoleculeData import MacromoleculeData
if TYPE_CHECKING:
    from .MacromoleculeSample import MacromoleculeSample

class Macromolecule(MacromoleculeData, Sample):
    """MXLIMS pydantic model class for Macromolecule
    """
        
    mxlims_type: Literal["Macromolecule"] = Field(
        "Macromolecule",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
        frozen=True,
    )
    
    @property
    def child_samples(self) -> list[MacromoleculeSample]:
        """getter for Macromolecule.child_samples list"""
        return self._get_link_1n("Sample", "parent_sample_id")

    @child_samples.setter
    def child_samples(self, values: list[MacromoleculeSample]):
        """setter for Macromolecule.child_samples list"""
        from .MacromoleculeSample import MacromoleculeSample

        for obj in values:
            if not isinstance(obj, MacromoleculeSample):
                raise ValueError("%s is not of type MacromoleculeSample" % obj)
        self._set_link_1n_rev("Sample", "parent_sample_id", values)
