# generated by datamodel-codegen:
#   filename:  objects/MxExperiment.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from ..rawobjects.RawMxExperiment import RawMxExperiment
from . import CollectionSweep, ReflectionSet


class MxExperiment(RawMxExperiment):
    """
    Crystallography experiment, with typed JSON containment lists
    """

    results: Optional[List[CollectionSweep]] = None
    template_data: Optional[List[CollectionSweep]] = Field(None, alias="templateData")
    reference_data: Optional[List[ReflectionSet]] = Field(None, alias="referenceData")
    subjobs: Optional[List[MxExperiment]] = None


MxExperiment.model_rebuild()
