# generated by mxlims/impl/generate_code.py
#  filename PinPosition.py

from __future__ import annotations
from pydantic import Field
from typing import Any, Literal, Optional, Union, TYPE_CHECKING
from ..objects.LogisticalSample import LogisticalSample
from ..data.PinPositionData import PinPositionData
if TYPE_CHECKING:
    from .CollectionSweep import CollectionSweep
    from .Crystal import Crystal
    from .MacromoleculeSample import MacromoleculeSample
    from .MultiPin import MultiPin
    from .MxExperiment import MxExperiment
    from .MxProcessing import MxProcessing
    from .ReflectionSet import ReflectionSet
    from .VolumeScan import VolumeScan

class PinPosition(PinPositionData, LogisticalSample):
    """MXLIMS pydantic model class for PinPosition
    """
        
    mxlims_type: Literal["PinPosition"] = Field(
        "PinPosition",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
        frozen=True,
    )
    
    @property
    def container(self) -> Optional[MultiPin]:
        """getter for PinPosition.container"""
        return self._get_link_n1("LogisticalSample", "container_id")

    @container.setter
    def container(self, value: Optional[MultiPin]):
        """setter for PinPosition.container"""
        from .MultiPin import MultiPin

        if value is None or isinstance(value, MultiPin):
            self._set_link_n1("LogisticalSample", "container_id", value)
        else:
            raise ValueError("container must be of type MultiPin or None")

    @property
    def contents(self) -> list[Crystal]:
        """getter for PinPosition.contents list"""
        return self._get_link_1n("LogisticalSample", "container_id")

    @contents.setter
    def contents(self, values: list[Crystal]):
        """setter for PinPosition.contents list"""
        from .Crystal import Crystal

        for obj in values:
            if not isinstance(obj, Crystal):
                raise ValueError("%s is not of type Crystal" % obj)
        self._set_link_1n_rev("LogisticalSample", "container_id", values)

    @property
    def datasets(self) -> list[Union[CollectionSweep, ReflectionSet]]:
        """getter for PinPosition.datasets list"""
        return self._get_link_1n("Dataset", "logistical_sample_id")

    @datasets.setter
    def datasets(self, values: list[Union[CollectionSweep, ReflectionSet]]):
        """setter for PinPosition.datasets list"""
        from .CollectionSweep import CollectionSweep
        from .ReflectionSet import ReflectionSet

        for obj in values:
            if not isinstance(obj, Union[CollectionSweep, ReflectionSet]):
                raise ValueError("%s is not of type Union[CollectionSweep, ReflectionSet]" % obj)
        self._set_link_1n_rev("Dataset", "logistical_sample_id", values)

    @property
    def jobs(self) -> list[Union[MxExperiment, MxProcessing, VolumeScan]]:
        """getter for PinPosition.jobs list"""
        return self._get_link_1n("Job", "logistical_sample_id")

    @jobs.setter
    def jobs(self, values: list[Union[MxExperiment, MxProcessing, VolumeScan]]):
        """setter for PinPosition.jobs list"""
        from .MxExperiment import MxExperiment
        from .MxProcessing import MxProcessing
        from .VolumeScan import VolumeScan

        for obj in values:
            if not isinstance(obj, Union[MxExperiment, MxProcessing, VolumeScan]):
                raise ValueError("%s is not of type Union[MxExperiment, MxProcessing, VolumeScan]" % obj)
        self._set_link_1n_rev("Job", "logistical_sample_id", values)

    @property
    def sample(self) -> Optional[MacromoleculeSample]:
        """getter for PinPosition.sample"""
        return self._get_link_n1("Sample", "sample_id")

    @sample.setter
    def sample(self, value: Optional[MacromoleculeSample]):
        """setter for PinPosition.sample"""
        from .MacromoleculeSample import MacromoleculeSample

        if value is None or isinstance(value, MacromoleculeSample):
            self._set_link_n1("Sample", "sample_id", value)
        else:
            raise ValueError("sample must be of type MacromoleculeSample or None")
