# generated by datamodel-codegen:
#   filename:  objects/Plate.json

from __future__ import annotations

from typing import Optional

from pydantic import Field

from ..data.PlateData import PlateData
from ..references.ShipmentRef import ShipmentRef
from .LogisticalSample import LogisticalSample


class Plate(PlateData, LogisticalSample):
    """
    A crystallization plate, with typed JSON containment lists
    """

    sample_ref: None = Field(None, alias="sampleRef")
    container_ref: Optional[ShipmentRef] = Field(None, alias="containerRef")
