# generated by datamodel-codegen:
#   filename:  objects/PlateWell.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import Field

from ..rawobjects.RawPlateWell import RawPlateWell
from . import MxExperiment, MxProcessing, WellDrop


class PlateWell(RawPlateWell):
    """
    A well in a crystallization plate, with typed JSON containment lists
    """

    contents: Optional[List[WellDrop]] = Field(None, min_length=1)
    jobs: Optional[List[Union[MxExperiment, MxProcessing]]] = None
