# generated by mxlims/scripts
#  filename Plate.py

from __future__ import annotations
from typing import Optional, Union
from ..core.LogisticalSample import LogisticalSample
from ..data.LogisticalSampleData import LogisticalSampleData
from ..data.PlateData import PlateData
from .PlateWell import PlateWell
from .Shipment import Shipment

class Plate(PlateData, LogisticalSampleData, LogisticalSample):
    """MXLIMS pydantic model class for Plate
    """
    
    @property
    def container(self) -> Optional[Shipment]:
        """getter for Plate.container"""
        return self.objects_by_id["LogisticalSample"].get(self.container_id)
    
    @container.setter
    def container(self, value: Optional[Shipment]):
        """setter for Plate.container"""
        if value:
            if not isinstance(value, Shipment):
                raise ValueError(
                    "container must be of type Shipment"
                )
            self.container_id = value.uuid
        else:
            self.container_id = None

    @property
    def contents(self) -> list[PlateWell]:
        """getter for Plate.contents list"""
        uid = self.uuid
        result = []
        for obj in self.objects_by_id["LogisticalSample"]:
            if uid == obj.container_id:
                result.append(obj)
        return result
    