# generated by datamodel-codegen:
#   filename:  objects/PlateWell.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import Field

from ..rawobjects.RawPlateWell import RawPlateWell
from .MxExperiment import MxExperiment
from .MxProcessing import MxProcessing
from .WellDrop import WellDrop


class PlateWell(RawPlateWell):
    """
    A well in a crystallization plate, with typed JSON containment lists
    """

    contents: Optional[List[WellDrop]] = Field(None, min_length=1)
    jobs: Optional[List[Union[MxExperiment, MxProcessing]]] = None
