# generated by datamodel-codegen:
#   filename:  objects/PlateShipment.json

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from ..rawobjects.RawShipment import RawShipment
from . import Plate


class PlateShipment(RawShipment):
    """
    Shipment of Plates, with typed JSON containment lists
    """

    contents: Optional[List[Plate]] = Field(None, min_length=1)
