# generated by datamodel-codegen:
#   filename:  objects/ReflectionSet.json

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from ..rawobjects.RawReflectionSet import RawReflectionSet


class ReflectionSet(RawReflectionSet):
    """
    Set of processed reflections, possibly merged or scaled, as might be stored within a MTZ or mmCIF reflection file
    """

    derived_data_sets: Optional[List[ReflectionSet]] = Field(
        None, alias="derivedDataSets"
    )


ReflectionSet.model_rebuild()
