# generated by datamodel-codegen:
#   filename:  objects/Shipment.json

from __future__ import annotations

from typing import Optional

from pydantic import Field

from ..core.LogisticalSample import LogisticalSample
from ..data.ShipmentData import ShipmentData


class Shipment(ShipmentData, LogisticalSample):
    """
    Shipment of Plates or Dewars
    """

    sample_ref: None = Field(None, alias="sampleRef")
    container_ref: None = Field(None, alias="containerRef")
