# generated by mxlims/impl/generate_code.py
#  filename VolumeScan.py

from __future__ import annotations
from pydantic import Field
from typing import Any, Literal, Optional, Union, TYPE_CHECKING
from ..objects.Job import Job
from ..data.VolumeScanData import VolumeScanData
if TYPE_CHECKING:
    from .CollectionSweep import CollectionSweep
    from .Crystal import Crystal
    from .DropRegion import DropRegion
    from .MacromoleculeSample import MacromoleculeSample
    from .MxExperiment import MxExperiment
    from .Pin import Pin
    from .PinPosition import PinPosition
    from .PlateWell import PlateWell
    from .WellDrop import WellDrop

class VolumeScan(VolumeScanData, Job):
    """MXLIMS pydantic model class for VolumeScan
    """
        
    mxlims_type: Literal["VolumeScan"] = Field(
        "VolumeScan",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
        frozen=True,
    )
    
    @property
    def logistical_sample(self) -> Optional[Union[Crystal, DropRegion, Pin, PinPosition, PlateWell, WellDrop]]:
        """getter for VolumeScan.logistical_sample"""
        return self._get_link_n1("LogisticalSample", "logistical_sample_id")

    @logistical_sample.setter
    def logistical_sample(self, value: Optional[Union[Crystal, DropRegion, Pin, PinPosition, PlateWell, WellDrop]]):
        """setter for VolumeScan.logistical_sample"""
        from .Crystal import Crystal
        from .Pin import Pin
        from .PinPosition import PinPosition
        from .PlateWell import PlateWell
        from .WellDrop import WellDrop
        from .DropRegion import DropRegion

        if value is None or isinstance(value, Union[Crystal, DropRegion, Pin, PinPosition, PlateWell, WellDrop]):
            self._set_link_n1("LogisticalSample", "logistical_sample_id", value)
        else:
            raise ValueError("logistical_sample must be of type Union[Crystal, DropRegion, Pin, PinPosition, PlateWell, WellDrop] or None")

    @property
    def sample(self) -> Optional[MacromoleculeSample]:
        """getter for VolumeScan.sample"""
        return self._get_link_n1("Sample", "sample_id")

    @sample.setter
    def sample(self, value: Optional[MacromoleculeSample]):
        """setter for VolumeScan.sample"""
        from .MacromoleculeSample import MacromoleculeSample

        if value is None or isinstance(value, MacromoleculeSample):
            self._set_link_n1("Sample", "sample_id", value)
        else:
            raise ValueError("sample must be of type MacromoleculeSample or None")

    @property
    def started_from(self) -> Optional[MxExperiment]:
        """getter for VolumeScan.started_from"""
        return self._get_link_n1("Job", "started_from_id")

    @property
    def template_data(self) -> list[CollectionSweep]:
        """getter for VolumeScan.template_data list"""
        return self._get_link_nn("Dataset", "template_data_ids")

    @template_data.setter
    def template_data(self, values: list[CollectionSweep]):
        """setter for VolumeScan.template_data list"""
        from .CollectionSweep import CollectionSweep

        for obj in values:
            if not isinstance(obj, CollectionSweep):
                raise ValueError("%s is not of type CollectionSweep" % obj)
        self._set_link_nn("Dataset", "template_data_ids", values)

    def append_template_data(self, value: CollectionSweep):
        """append to VolumeScan.template_data list"""
        from .CollectionSweep import CollectionSweep

        if isinstance(value, CollectionSweep):
            self._append_link_nn("template_data_ids", value)
        else:
            raise ValueError("%s is not of type CollectionSweep" % value)

    def remove_template_data(self, value: CollectionSweep):
        """remove from VolumeScan.template_data list"""
        from .CollectionSweep import CollectionSweep

        if isinstance(value, CollectionSweep):
            self._remove_link_nn("template_data_ids", value)
        else:
            raise ValueError("%s is not of type CollectionSweep" % value)
