# generated by datamodel-codegen:
#   filename:  objects/WellDrop.json

from __future__ import annotations

from typing import Optional

from pydantic import Field

from ..core.LogisticalSample import LogisticalSample
from ..data.PlateWellData import PlateWellData
from ..references.CrystallographicSampleRef import CrystallographicSampleRef
from ..references.PlateWellRef import PlateWellRef


class WellDrop(PlateWellData, LogisticalSample):
    """
    A drop in a well in a crystallization plate with typed JSON containment lists
    """

    sample_ref: Optional[CrystallographicSampleRef] = Field(None, alias="sampleRef")
    container_ref: Optional[PlateWellRef] = Field(None, alias="containerRef")
