---
name: mxlims
channels:
  - conda-forge
dependencies:
  - python=3.10,<3.12
  - pip
  - poetry ==2.2.1
  - pip:
      - ruff
      - yamllint
      - packaging
      - json-schema-for-humans
      - jsonschema>=4.18.0
      - ruamel.yaml==0.17.21
      - pydantic==2.8.2
      - datamodel-code-generator>=0.76.1
      - --editable /home/rhfogh/pycharm/mxlims_data_model
