# generated by datamodel-codegen:
#   filename:  core/Job.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from ..datatypes import JobStatus
from .MxlimsObject import MxlimsObject


class Job(MxlimsObject):
    """
    Base class for MXLIMS Jobs - an experiment or calculation producing Datasets
    """

    start_time: Optional[datetime] = Field(
        None,
        alias="startTime",
        description="Actual starting time for job or calculation, ",
        title="Start Time",
    )
    end_time: Optional[datetime] = Field(
        None,
        alias="endTime",
        description="Actual finishing time for job or calculation, ",
        title="End Time",
    )
    job_status: Optional[JobStatus] = Field(
        None,
        alias="jobStatus",
        description="Status of job - enumerated, ",
        examples=["Template", "Ready", "Running", "Completed", "Failed", "Aborted"],
    )
    sample_id: Optional[UUID] = Field(
        None,
        alias="sampleId",
        description="String UUID of the PreparedSample that applies to this Job",
        title="Sample Id",
    )
    logistical_sample_id: Optional[UUID] = Field(
        None,
        alias="logisticalSampleId",
        description="String UUID of LogisticalSample relevant to this Job.",
        title="Logistical Sample Id",
    )
    started_from_id: Optional[UUID] = Field(
        None,
        alias="startedFromId",
        description="String UUID of the Job from which this Job was started.",
        title="Started From Id",
    )
    input_data_ids: Optional[List[UUID]] = Field(
        None,
        alias="inputDataIds",
        description="String UUID of input Datasets for this Job. For pure Database implementations this field is replaced bu JobInputLinks.",
        title="Input Data Ids",
    )
    reference_data_ids: Optional[List[UUID]] = Field(
        None,
        alias="referenceDataIds",
        description="String UUID of reference Datasets for this Job. For pure Database implementations this field is replaced bu JobInputLinks.",
        title="Reference Data Ids",
    )
    template_data_ids: Optional[List[UUID]] = Field(
        None,
        alias="templateDataIds",
        description="String UUID of template Datasets for this Job. For pure Database implementations this field is replaced bu JobInputLinks.",
        title="Template Data Ids",
    )
