# generated by datamodel-codegen:
#   filename:  core/Job.json

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field


class Job(BaseModel):
    """
    Base class for MXLIMS Jobs - an experiment or calculation producing Datasets
    """

    sample_id: Optional[UUID] = Field(
        None, alias="sampleId", description="uuid for related sample", title="SampleId"
    )
    started_from_id: Optional[UUID] = Field(
        None,
        alias="startedFromId",
        description="uuid for JOPb from which this Job was started",
        title="StartedFromId",
    )
    logistical_sample_id: Optional[UUID] = Field(
        None,
        alias="logisticalSampleId",
        description="uuid for LogisticalSample related to Job",
        title="LogisticalSampleId",
    )
    reference_data_ids: List[UUID] = Field(
        default_factory=list,
        alias="referenceDataIds",
        description="uuid for reference Datasets",
        title="ReferenceDataId",
    )
    template_data_ids: List[UUID] = Field(
        default_factory=list,
        alias="templateDataIds",
        description="uuid for template Datasets",
        title="TemplateDataId",
    )
    input_data_ids: List[UUID] = Field(
        default_factory=list,
        alias="inputDataIds",
        description="uuid for input Datasets",
        title="InputDataId",
    )
