# generated by datamodel-codegen:
#   filename:  core/JobInputLink.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field

from ..datatypes import JobInputRole


class JobInputLink(BaseModel):
    """
    Model for handling Job-Dataset many-to-many links in database implementations (only)
    """

    role: JobInputRole = Field(
        ..., description="Role determining which Job-Dataset link this object describes"
    )
    job_id: UUID = Field(
        ...,
        alias="jobId",
        description="String UUID of Job involved in this link.",
        title="JobId",
    )
    dataset_id: UUID = Field(
        ...,
        alias="datasetId",
        description="String UUID of Dataset involved in this link.",
        title="DatasetId",
    )
