# generated by datamodel-codegen:
#   filename:  core/LogisticalSample.json

from __future__ import annotations

from typing import Optional
from uuid import UUID

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field


class LogisticalSample(BaseModel):
    """
    Base class for MXLIMS Logistical Samples

    describing Sample containers and locations
    (from Dewars and Plates to drops, pins and crystals)
    """

    sample_id: Optional[UUID] = Field(
        None,
        alias="sampleId",
        description="uuid for constituent sample",
        title="SampleId",
    )
    container_id: Optional[UUID] = Field(
        None,
        alias="containerId",
        description="uuid for LogisticalSample container",
        title="containerId",
    )
