# generated by datamodel-codegen:
#   filename:  core/NamespacedExtension.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class NamespacedExtension(BaseModel):
    """
    JSON schema for extending MxlimsData. To be subclassed
    """

    namespace: str = Field(
        ...,
        description="Namespace string defining 'owner' of the namespace, e.g. 'ESRF, 'GPhL",
        title="Namespace",
    )
