# generated by datamodel-codegen:
#   filename:  core/PreparedSample.json

from __future__ import annotations

from mxlims.pydantic.MxBaseModel import BaseModel


class PreparedSample(BaseModel):
    """
    Base class for MXLIMS Prepared Samples describing Sample content
    """
