# generated by datamodel-codegen:
#   filename:  core/PreparedSample.json

from __future__ import annotations

from .MxlimsObject import MxlimsObject


class PreparedSample(MxlimsObject):
    """
    Base class for MXLIMS Prepared Samples describing Sample content
    """
