# generated by datamodel-codegen:
#   filename:  data/DatasetData.json

from __future__ import annotations

from pydantic import Field

from .MxlimsObjectData import MxlimsObjectData


class DatasetData(MxlimsObjectData):
    """
    Base class for MXLIMS Datasets
    """

    role: str | None = Field(
        None,
        description="Role of Dataset relative to the source Job. Intended for filtering of Datasets",
        examples=["Result", "Intermediate", "Characterisation", "Centring"],
        title="Role",
    )
