# generated by datamodel-codegen:
#   filename:  data/LogisticalSampleData.json

from __future__ import annotations

from .MxlimsObjectData import MxlimsObjectData


class LogisticalSampleData(MxlimsObjectData):
    """
    Base class for MXLIMS Logistical Samples

    describing Sample containers and locations
    (from Dewars and Plates to drops, pins and crystals)
    """
