# generated by datamodel-codegen:
#   filename:  data/LogisticalSampleData.json

from __future__ import annotations

from .MxlimsObjectData import MxlimsObjectData

LogisticalSampleData = MxlimsObjectData
