# generated by datamodel-codegen:
#   filename:  data/MacromoleculeSampleData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel


class MacromoleculeSampleData(BaseModel):
    """
    Sample consisting of a macromolecule in a medium, with additional components
    """
