# generated by datamodel-codegen:
#   filename:  data/MxExperimentData.json

from __future__ import annotations

from typing import Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, NonNegativeInt, PositiveFloat, PositiveInt, confloat

from ..datatypes.SpaceGroupName import SpaceGroupName
from ..datatypes.UnitCell import UnitCell


class MxExperimentData(BaseModel):
    """
    Crystallography experiment, producing data
    """

    experiment_strategy: Optional[str] = Field(
        None,
        alias="experimentStrategy",
        description="Experiment strategy indicator",
        examples=[
            "OSC",
            "Helical",
            "MXPressE",
            "GPhL.native.basic",
            "GPhL.SAD.advanced",
            "GPhL.2wvlMAD.basic",
        ],
        title="Experiment Strategy",
    )
    experiment_location: Optional[str] = Field(
        None,
        alias="experimentLocation",
        description="Place where experiment is performed",
        examples=["SOLEIL PX2", "ESRF MASSIF-1"],
        title="Experiment Location",
    )
    expected_resolution: Optional[PositiveFloat] = Field(
        None,
        alias="expectedResolution",
        description="The resolution expected in the experiment - for positioning the detector and setting up the experiment",
        title="Expected Resolution",
    )
    required_resolution: Optional[PositiveFloat] = Field(
        None,
        alias="requiredResolution",
        description="The minimum resolution required to carry on with the experiment",
        title="Required Resolution",
    )
    target_completeness: Optional[confloat(le=100.0, gt=0.0)] = Field(
        None,
        alias="targetCompleteness",
        description="Minimal completeness expected from experiment",
        title="Target Completeness",
    )
    target_multiplicity: Optional[PositiveFloat] = Field(
        None,
        alias="targetMultiplicity",
        description="Minimal multiplicity expected from experiment",
        title="Target Multiplicity",
    )
    aimed_total_range: Optional[PositiveFloat] = Field(
        None,
        alias="aimedTotalRange",
        description="The desired total experiment length (in degrees rotated) ",
        title="Aimed Total Range",
    )
    priority: Optional[PositiveInt] = Field(
        None,
        description="Priority of experiment - smaller number higher priority",
        title="Priority",
    )
    energy: Optional[PositiveFloat] = Field(
        None, description="Desired energy of the beam in eV", title="Energy"
    )
    dose_budget: Optional[PositiveFloat] = Field(
        None,
        alias="doseBudget",
        description="Dose (MGy) to be used in experiment",
        title="Dose Budget",
    )
    radiation_sensitivity: Optional[confloat(le=1.0, gt=0.0)] = Field(
        None,
        alias="radiationSensitivity",
        description="Predicted relative radiation sensitivity of sample at target wavelength.",
        title="Radiation Sensitivity",
    )
    snapshot_count: Optional[NonNegativeInt] = Field(
        0,
        alias="snapshotCount",
        description="Number of snapshots to acquire after each (re)centring",
        title="Snapshot Count",
    )
    wedge_width: Optional[PositiveFloat] = Field(
        None,
        alias="wedgeWidth",
        description="Wedge width (in degrees) to use for interleaving",
        title="Wedge Width",
    )
    measured_flux: Optional[PositiveFloat] = Field(
        None,
        alias="measuredFlux",
        description="Measured value of beam flux in photons/s",
        title="Measured Flux",
    )
    radiation_dose: Optional[PositiveFloat] = Field(
        None,
        alias="radiationDose",
        description="Total radiation dose absorbed during experiment",
        title="Radiation Dose",
    )
    expected_space_group_name: Optional[SpaceGroupName] = Field(
        None,
        alias="expectedSpaceGroupName",
        description="Name of space group expected to be present. Names may include alternative settings. Matches mmCIF item symmetry.space_group_name_H-M (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_symmetry.space_group_name_H-M.html).",
        title="Space Group Name",
    )
    expected_unit_cell: Optional[UnitCell] = Field(
        None,
        alias="expectedUnitCell",
        description="Unit cell of crystal expected to be present.",
    )
    selected_space_group_name: Optional[SpaceGroupName] = Field(
        None,
        alias="selectedSpaceGroupName",
        description="Name of space group, as determined during characterisation. Names may include alternative settings. Matches mmCIF item symmetry.space_group_name_H-M (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_symmetry.space_group_name_H-M.html).",
        title="Space Group Name",
    )
    selected_unit_cell: Optional[UnitCell] = Field(
        None,
        alias="selectedUnitCell",
        description="Unit cell of crystal, as determined during characterisation.",
    )
