# generated by datamodel-codegen:
#   filename:  data/MxlimsObjectData.json

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from .NamespacedExtensionData import NamespacedExtensionData


class MxlimsObjectData(BaseModel):
    """
    Base object for all MXLIMS objects: Job, Dataset, PreparedSample, and LogisticalSample
    """

    version: Literal["0.6.2"] = Field(
        "0.6.2", description="MXLIMS version for current model", title="Version"
    )
    mxlims_type: str = Field(
        ...,
        alias="mxlimsType",
        description="The type of the MXLIMS object. Fixed for each subtype schema",
        title="MxlimsType",
    )
    mxlims_base_type: str = Field(
        ...,
        alias="mxlimsBaseType",
        description="The abstract (super)type of the MXLIMS object. Fixed for each subtype schema",
        title="MxlimsBaseType",
    )
    uuid: UUID = Field(
        ..., description="Permanent unique identifier string", title="Uuid"
    )
    namespaced_extensions: Optional[List[NamespacedExtensionData]] = Field(
        None,
        alias="namespacedExtensions",
        description="List of extensions to metadata, each defined in a NamespacedExtension schema",
        title="Namespaced Extensions",
    )
    extensions: Optional[Dict[str, Any]] = Field(
        None,
        description="Keyword-value dictionary string:Any of extensions. Use is accepted but discouraged",
        title="Extensions",
    )
