# generated by datamodel-codegen:
#   filename:  data/MxlimsObjectData.json

from __future__ import annotations

from typing import Any, Dict, Optional
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, constr


class MxlimsObjectData(BaseModel):
    """
    Base object for all MXLIMS objects: Job, Dataset, Sample, and LogisticalSample
    """

    mxlims_type: str = Field(
        ...,
        alias="mxlimsType",
        description="The type of the MXLIMS object. Fixed for each subtype schema",
        title="MxlimsType",
    )
    mxlims_base_type: Optional[str] = Field(
        None,
        alias="mxlimsBaseType",
        description="The core type of the MXLIMS object (Job, Dataset, Sample, or LogisticalSample). Fixed for each subtype schema",
        title="MxlimsBaseType",
    )
    uuid: Optional[UUID] = Field(
        None, description="Permanent unique identifier string", title="Uuid"
    )
    extensions: Optional[Dict[str, Dict[str, Any]]] = Field(
        None,
        description="Keyword-value dictionary string:object of extensions. The key must be a valid domain name pointing to the site 'owning' the extensions, but need bw resovable.",
        title="Extensions",
    )
    identifiers: Optional[
        Dict[
            str,
            constr(
                pattern=r"^(?i)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
            ),
        ]
    ] = Field(
        None,
        description="Keyword-value dictionary string:string of site-specific object indentifiers. The key must be a valid domain name pointing to the site 'owning' the extensions, but need bw resovable.",
        title="Identifiers",
    )
    urls: Optional[
        Dict[
            str,
            constr(
                pattern=r"^(?i)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
            ),
        ]
    ] = Field(
        None,
        description="Keyword-value dictionary string:urlstring of site-specific object urls. The key must be a valid domain name pointing to the site 'owning' the extensions, but need bw resovable.",
        title="Urls",
    )
    annotation: Optional[str] = Field(None, description="Comment or annotation.")
