# generated by datamodel-codegen:
#   filename:  data/MxProcessingData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from ..datatypes.SpaceGroupName import SpaceGroupName
from ..datatypes.UnitCell import UnitCell


class MxProcessingData(BaseModel):
    """
    Crystallography Processing calculation,
    """

    program_name: str | None = Field(
        None,
        alias="programName",
        description="Name of processing program",
        title="Program name",
    )
    program_version: str | None = Field(
        None,
        alias="programVersion",
        description="Version of processing program",
        title="Program version",
    )
    space_group_name: SpaceGroupName | None = Field(
        None,
        alias="spaceGroupName",
        description="Name of space group, to use for processing input. Names may include alternative settings. Matches mmCIF item symmetry.space_group_name_H-M (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_symmetry.space_group_name_H-M.html).",
        title="Space Group Name",
    )
    unit_cell: UnitCell | None = Field(
        None,
        alias="unitCell",
        description="Unit cell of crystal, to use for processing input.",
    )
