# generated by datamodel-codegen:
#   filename:  data/PinData.json

from __future__ import annotations

from typing import Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, PositiveInt


class PinData(BaseModel):
    """
    A Pin mounted on a puck with a single slot for crystals.
    """

    barcode: Optional[str] = Field(None, description="The Pin barcode or RFID code")
    position_in_puck: PositiveInt = Field(
        ...,
        alias="positionInPuck",
        description="The puck position occupied by the pin. This should be validated against the puck's numberPositions property.",
        examples=[16],
    )
    loop_type: Optional[str] = Field(
        None,
        alias="loopType",
        description="Type of loop. NB should be made into an enum",
        title="Loop type",
    )
    holder_length: Optional[float] = Field(
        None,
        alias="holderLength",
        description="Holder length in mm",
        title="Holder length",
    )
