# generated by datamodel-codegen:
#   filename:  data/PinPositionData.json

from __future__ import annotations

from typing import Literal

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field, conint


class PinPositionData(BaseModel):
    """
    An independent Position within a Pin where crystals can be located.
    """

    mxlims_type: Literal["PinPosition"] = Field(
        "PinPosition",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
    )
    position_in_pin: conint(ge=1) = Field(
        ...,
        alias="positionInPin",
        description="The pin position within  the pin. This should be validated against the pin's numberPositions property.",
        examples=[4],
    )
