# generated by datamodel-codegen:
#   filename:  data/PlateData.json

from __future__ import annotations

from typing import Dict, Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from ..datatypes.PlateType import PlateType
from ..datatypes.TrackingDevice import TrackingDevice


class PlateData(BaseModel):
    """
    A crystallization plate
    """

    barcode: Optional[str] = Field(
        None, description="The plate barcode or other identifier"
    )
    plate_type: Optional[PlateType] = Field(
        None, alias="plateType", description="Plate type description object"
    )
    identifiers: Optional[Dict[str, str]] = Field(
        None,
        description="Dictionary str:str of contextName: identifier. ContextName will typically refer to a LIMS, database, or web site but could also be e.g. 'smiles' or 'sequence'",
        title="Identifiers",
    )
    tracking_device: Optional[TrackingDevice] = Field(
        None, alias="trackingDevice", description="Plate tracking device"
    )
