# generated by datamodel-codegen:
#   filename:  data/PreparedSampleData.json

from __future__ import annotations

from .MxlimsObjectData import MxlimsObjectData


class PreparedSampleData(MxlimsObjectData):
    """
    Base class for MXLIMS Prepared Samples describing Sample content
    """
