# generated by datamodel-codegen:
#   filename:  data/PuckData.json

from __future__ import annotations

from typing import Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, conint


class PuckData(BaseModel):
    """
    A puck containing mounted crystals on pins.
    """

    barcode: Optional[str] = Field(None, description="The Puck barcode or RFID code")
    number_positions: conint(ge=1) = Field(
        ...,
        alias="numberPositions",
        description="The number of pin positions available.",
    )
    puck_type: Optional[str] = Field(
        None, alias="puckType", description="The Puck type (should be made an enum)"
    )
