# generated by datamodel-codegen:
#   filename:  data/PuckData.json

from __future__ import annotations

from typing import Literal, Optional

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field, conint


class PuckData(BaseModel):
    """
    A puck containing mounted crystals on pins.
    """

    mxlims_type: Literal["Puck"] = Field(
        "Puck",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="MxlimsType",
    )
    barcode: Optional[str] = Field(None, description="The Puck barcode or RFID code")
    number_positions: conint(ge=1) = Field(
        ...,
        alias="numberPositions",
        description="The number of pin positions available.",
    )
