# generated by datamodel-codegen:
#   filename:  data/ShipmentData.json

from __future__ import annotations

from typing import Dict, Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, PositiveInt

from ..datatypes.Person import Person
from ..datatypes.TrackingDevice import TrackingDevice


class ShipmentData(BaseModel):
    """
    Shipment
    """

    proposal_code: str = Field(
        ...,
        alias="proposalCode",
        description="The proposal number at the receiving facility.",
        examples=["mx1234"],
    )
    session_number: Optional[PositiveInt] = Field(
        None,
        alias="sessionNumber",
        description="The session number within the proposal. If this property is not set, the shipment is for unattended collection.",
    )
    lab_contact_outbound: Optional[Person] = Field(
        None, alias="labContactOutbound", description="Lab contact outbound"
    )
    lab_contact_return: Optional[Person] = Field(
        None, alias="labContactReturn", description="Lab contact for return"
    )
    identifiers: Optional[Dict[str, str]] = Field(
        None,
        description="Dictionary str:str of contextName: identifier. ContextName will typically refer to a LIMS, database, or web site but could also be e.g. 'smiles' or 'sequence'",
        title="Identifiers",
    )
    tracking_device: Optional[TrackingDevice] = Field(
        None, alias="trackingDevice", description="Shipment tracking device"
    )
