# generated by datamodel-codegen:
#   filename:  data/ShipmentData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, PositiveInt

from ..datatypes.Person import Person
from ..datatypes.TrackingDevice import TrackingDevice


class ShipmentData(BaseModel):
    """
    Shipment
    """

    proposal_code: str = Field(
        ...,
        alias="proposalCode",
        description="The proposal number at the receiving facility.",
        examples=["mx1234"],
    )
    session_number: PositiveInt | None = Field(
        None,
        alias="sessionNumber",
        description="The session number within the proposal. If this property is not set, the shipment is for unattended collection.",
    )
    lab_contact_outbound: Person | None = Field(
        None, alias="labContactOutbound", description="Lab contact outbound"
    )
    lab_contact_return: Person | None = Field(
        None, alias="labContactReturn", description="Lab contact for return"
    )
    tracking_device: TrackingDevice | None = Field(
        None, alias="trackingDevice", description="Shipment tracking device"
    )
