# generated by datamodel-codegen:
#   filename:  data/WellDropData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, conint


class WellDropData(BaseModel):
    """
    A drop in a well in a crystallization plate
    """

    drop_number: conint(ge=1) = Field(
        ...,
        alias="dropNumber",
        description="The drop number. This should be validated against the plateType's numberSubPositions property.",
    )
