# generated by datamodel-codegen:
#   filename:  messages/BaseMessageData.json

from __future__ import annotations

from typing import Literal

from mxlims.impl.MxlimsImplementation import BaseMessage
from pydantic import Field, RootModel


class Version(RootModel[Literal["0.6.13"]]):
    root: Literal["0.6.13"] = Field(
        "0.6.13", description="MXLIMS version for current model", title="Version"
    )


class BaseMessageData(BaseMessage):
    """
    Base data object for all MXLIMS messages
    """

    version: Literal["0.6.13"] = Field(
        "0.6.13", description="MXLIMS version for current model", title="Version"
    )
