# generated by datamodel-codegen:
#   filename:  messages/MxlimsMessage.json

from __future__ import annotations

from pydantic import ConfigDict, Field

from ..datatypes.DatasetStub import DatasetStub
from ..datatypes.JobStub import JobStub
from ..datatypes.LogisticalSampleStub import LogisticalSampleStub
from ..datatypes.SampleStub import SampleStub
from .MxlimsMessageStrict import MxlimsMessageStrict


class MxlimsMessage(MxlimsMessageStrict):
    """
    Message containing all possible objects, by type
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dataset: dict[str, DatasetStub] | None = Field(
        default_factory=dict,
        alias="Dataset",
        description="idString:object dictionary of Dataset stubs.",
        title="Datasets",
    )
    job: dict[str, JobStub] | None = Field(
        default_factory=dict,
        alias="Job",
        description="idString:object dictionary of Job stubs.",
        title="Jobs",
    )
    logistical_sample: dict[str, LogisticalSampleStub] | None = Field(
        default_factory=dict,
        alias="LogisticalSample",
        description="idString:object dictionary of LogisticalSample stubs.",
        title="LogisticalSamples",
    )
    sample: dict[str, SampleStub] | None = Field(
        default_factory=dict,
        alias="Sample",
        description="idString:object dictionary of Sample stubs.",
        title="Samples",
    )
