# generated by datamodel-codegen:
#   filename:  messages/MxlimsMessageStrict.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from ..objects.CollectionSweep import CollectionSweep
from ..objects.Crystal import Crystal
from ..objects.Dewar import Dewar
from ..objects.DropRegion import DropRegion
from ..objects.Macromolecule import Macromolecule as Macromolecule_1
from ..objects.MacromoleculeSample import MacromoleculeSample as MacromoleculeSample_1
from ..objects.Medium import Medium
from ..objects.MultiPin import MultiPin
from ..objects.MxExperiment import MxExperiment
from ..objects.MxProcessing import MxProcessing
from ..objects.Pin import Pin
from ..objects.PinPosition import PinPosition
from ..objects.Plate import Plate
from ..objects.PlateWell import PlateWell
from ..objects.Puck import Puck
from ..objects.ReflectionSet import ReflectionSet
from ..objects.Shipment import Shipment
from ..objects.VolumeScan import VolumeScan
from ..objects.WellDrop import WellDrop
from .BaseMessageData import BaseMessageData


class MxlimsMessageStrict(BaseMessageData):
    """
    Message containing all possible objects, by type
    """

    collection_sweep: Annotated[
        dict[str, CollectionSweep] | None,
        Field(
            alias="CollectionSweep",
            description="idString:object dictionary of CollectionSweeps.",
            title="CollectionSweeps",
        ),
    ] = None
    crystal: Annotated[
        dict[str, Crystal] | None,
        Field(
            alias="Crystal",
            description="idString:object dictionary of Crystals.",
            title="Crystals",
        ),
    ] = None
    dewar: Annotated[
        dict[str, Dewar] | None,
        Field(
            alias="Dewar",
            description="idString:object dictionary of Dewars.",
            title="Dewars",
        ),
    ] = None
    drop_region: Annotated[
        dict[str, DropRegion] | None,
        Field(
            alias="DropRegion",
            description="idString:object dictionary of DropRegions.",
            title="DropRegions",
        ),
    ] = None
    macromolecule: Annotated[
        dict[str, Macromolecule_1] | None,
        Field(
            alias="Macromolecule",
            description="idString:object dictionary of Macromolecule (reference sample) objects.",
            title="Macromolecule",
        ),
    ] = None
    macromolecule_sample: Annotated[
        dict[str, MacromoleculeSample_1] | None,
        Field(
            alias="MacromoleculeSample",
            description="idString:object dictionary of Macromolecule-containing sample objects.",
            title="MacromoleculeSample",
        ),
    ] = None
    medium: Annotated[
        dict[str, Medium] | None,
        Field(
            alias="Medium",
            description="idString:object dictionary of Medium (sample) objects.",
            title="Media",
        ),
    ] = None
    mx_experiment: Annotated[
        dict[str, MxExperiment] | None,
        Field(
            alias="MxExperiment",
            description="idString:object dictionary of MxExperiments.",
            title="MxExperiments",
        ),
    ] = None
    mx_processing: Annotated[
        dict[str, MxProcessing] | None,
        Field(
            alias="MxProcessing",
            description="idString:object dictionary of MxProcessings.",
            title="MxProcessings",
        ),
    ] = None
    multi_pin: Annotated[
        dict[str, MultiPin] | None,
        Field(
            alias="MultiPin",
            description="idString:object dictionary of MultiPins.",
            title="MultiPins",
        ),
    ] = None
    pin: Annotated[
        dict[str, Pin] | None,
        Field(
            alias="Pin", description="idString:object dictionary of Pins.", title="Pins"
        ),
    ] = None
    pin_position: Annotated[
        dict[str, PinPosition] | None,
        Field(
            alias="PinPosition",
            description="idString:object dictionary of PinPositions.",
            title="PinPositions",
        ),
    ] = None
    plate: Annotated[
        dict[str, Plate] | None,
        Field(
            alias="Plate",
            description="idString:object dictionary of Plates.",
            title="Plates",
        ),
    ] = None
    plate_well: Annotated[
        dict[str, PlateWell] | None,
        Field(
            alias="PlateWell",
            description="idString:object dictionary of PlateWells.",
            title="PlateWells",
        ),
    ] = None
    puck: Annotated[
        dict[str, Puck] | None,
        Field(
            alias="Puck",
            description="idString:object dictionary of Pucks.",
            title="Pucks",
        ),
    ] = None
    reflection_set: Annotated[
        dict[str, ReflectionSet] | None,
        Field(
            alias="ReflectionSet",
            description="idString:object dictionary of ReflectionSets.",
            title="ReflectionSets",
        ),
    ] = None
    shipment: Annotated[
        dict[str, Shipment] | None,
        Field(
            alias="Shipment",
            description="idString:object dictionary of Shipments.",
            title="Shipments",
        ),
    ] = None
    volume_scan: Annotated[
        dict[str, VolumeScan] | None,
        Field(
            alias="VolumeScan",
            description="idString:object dictionary of VolumeScans.",
            title="VolumeScans",
        ),
    ] = None
    well_drop: Annotated[
        dict[str, WellDrop] | None,
        Field(
            alias="WellDrop",
            description="idString:object dictionary of WellDrops.",
            title="WellDrops",
        ),
    ] = None
