# generated by datamodel-codegen:
#   filename:  messages/MxlimsMessage.json

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field

from ..datatypes.DatasetStub import DatasetStub
from ..datatypes.JobStub import JobStub
from ..datatypes.LogisticalSampleStub import LogisticalSampleStub
from ..datatypes.SampleStub import SampleStub
from .MxlimsMessageStrict import MxlimsMessageStrict


class MxlimsMessage(MxlimsMessageStrict):
    """
    Message containing all possible objects, by type
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dataset: Annotated[
        dict[str, DatasetStub] | None,
        Field(
            alias="Dataset",
            description="idString:object dictionary of Dataset stubs.",
            title="Datasets",
        ),
    ] = None
    job: Annotated[
        dict[str, JobStub] | None,
        Field(
            alias="Job",
            description="idString:object dictionary of Job stubs.",
            title="Jobs",
        ),
    ] = None
    logistical_sample: Annotated[
        dict[str, LogisticalSampleStub] | None,
        Field(
            alias="LogisticalSample",
            description="idString:object dictionary of LogisticalSample stubs.",
            title="LogisticalSamples",
        ),
    ] = None
    sample: Annotated[
        dict[str, SampleStub] | None,
        Field(
            alias="Sample",
            description="idString:object dictionary of Sample stubs.",
            title="Samples",
        ),
    ] = None
