# generated by datamodel-codegen:
#   filename:  messages/ShipmentMessage.json

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field

from ..objects.Crystal import Crystal
from ..objects.Dewar import Dewar
from ..objects.DropRegion import DropRegion
from ..objects.Macromolecule import Macromolecule as Macromolecule_1
from ..objects.MacromoleculeSample import MacromoleculeSample as MacromoleculeSample_1
from ..objects.MultiPin import MultiPin
from ..objects.Pin import Pin
from ..objects.PinPosition import PinPosition
from ..objects.Plate import Plate
from ..objects.PlateWell import PlateWell
from ..objects.Puck import Puck
from ..objects.Shipment import Shipment
from ..objects.WellDrop import WellDrop
from .BaseMessageData import BaseMessageData


class ShipmentMessage(BaseMessageData):
    """
    Message containing a shipment of either frozen crystals or crystallization plates
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    shipment: Annotated[dict[str, Shipment], Field(alias="Shipment")]
    plate: Annotated[dict[str, Plate] | None, Field(alias="Plate")] = None
    plate_well: Annotated[
        dict[str, PlateWell] | None, Field(alias="PlateWell")
    ] = None
    well_drop: Annotated[dict[str, WellDrop] | None, Field(alias="WellDrop")] = None
    drop_region: Annotated[dict[str, DropRegion] | None, Field(alias="DropRegion")] = (
        None
    )
    dewar: Annotated[dict[str, Dewar] | None, Field(alias="Dewar")] = None
    puck: Annotated[dict[str, Puck] | None, Field(alias="Puck")] = None
    multi_pin: Annotated[dict[str, MultiPin] | None, Field(alias="MultiPin")] = None
    pin: Annotated[dict[str, Pin] | None, Field(alias="Pin")] = None
    pin_position: Annotated[
        dict[str, PinPosition] | None, Field(alias="PinPosition")
    ] = None
    macromolecule_sample: Annotated[
        dict[str, MacromoleculeSample_1], Field(alias="MacromoleculeSample")
    ]
    macromolecule: Annotated[dict[str, Macromolecule_1], Field(alias="Macromolecule")]
    crystal: Annotated[dict[str, Crystal] | None, Field(alias="Crystal")] = None
