# generated by datamodel-codegen:
#   filename:  datatypes/Circle.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, PositiveFloat

from . import Point


class Circle(BaseModel):
    """
    A circle marked on an image or in absolute plate space.
    """

    region_type: Literal["circle"] = Field(
        ..., alias="regionType", description="Type of region", title="Region type"
    )
    center: Point
    radius: PositiveFloat = Field(..., description="The radius of the circle.")
