# generated by datamodel-codegen:
#   filename:  datatypes/Circle.json

from __future__ import annotations

from typing import Literal

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field, PositiveFloat

from .Point import Point


class Circle(BaseModel):
    """
    A circle marked on an image or in absolute plate space.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    region_type: Literal["circle"] = Field(
        "circle", alias="regionType", description="Type of region", title="Region type"
    )
    center: Point
    radius: PositiveFloat = Field(..., description="The radius of the circle.")
