# generated by datamodel-codegen:
#   filename:  datatypes/DropImageData.json

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from .DropImage import DropImage


class DropImageData(DropImage):
    """
    DropImage, containing image as attached data.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    url: Any | None = None
    data: str = Field(..., description="The image, UUencoded.")
