# generated by datamodel-codegen:
#   filename:  datatypes/DropImageUrl.json

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, ConfigDict, Field

from .DropImage import DropImage


class DropImageUrl(DropImage):
    """
    DropImage, containing url pointing to image.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    data: Any | None = None
    url: AnyUrl = Field(
        ...,
        description="A URL where the image can be found ('file', 'http', ...). It is assumed that no further authentication is needed to read this image.",
    )
