# generated by datamodel-codegen:
#   filename:  datatypes/DropImageData.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import Field

from .DropImage import DropImage


class DropImageData(DropImage):
    """
    DropImage, containing image as attached data.
    """

    url: Optional[Any] = None
    data: str = Field(..., description="The image, UUencoded.")
