# generated by datamodel-codegen:
#   filename:  datatypes/ImageRegionUnit.json

from __future__ import annotations

from enum import Enum


class ImageRegionUnit(Enum):
    """
    Allowed units for image region images
    """

    MM = "mm"
    MICRON = "micron"
    PIXEL = "pixel"
