# generated by datamodel-codegen:
#   filename:  datatypes/ImageRegion.json

from __future__ import annotations

from typing import Optional, Union

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field

from .Circle import Circle
from .DropImageData import DropImageData
from .DropImageUrl import DropImageData as DropImageData_1
from .ImageRegionUnit import ImageRegionUnit
from .Line import Line
from .Point import Point
from .Polygon import Polygon
from .Rectangle import Rectangle


class ImageRegion(BaseModel):
    """
    A region marked on an image.
    """

    region: Union[Point, Circle, Line, Rectangle, Polygon]
    image: Optional[Union[DropImageData, DropImageData_1]] = None
    units: ImageRegionUnit = Field(
        ..., description="The units of the region's co-ordinates."
    )
