# generated by datamodel-codegen:
#   filename:  datatypes/ImageRegion.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field

from .Circle import Circle
from .DropImageData import DropImageData
from .DropImageUrl import DropImageUrl
from .ImageRegionUnit import ImageRegionUnit
from .Line import Line
from .Point import Point
from .Polygon import Polygon
from .Rectangle import Rectangle


class ImageRegion(BaseModel):
    """
    A region marked on an image.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    region: Point | Circle | Line | Rectangle | Polygon
    image: DropImageUrl | DropImageData
    units: ImageRegionUnit = Field(
        ..., description="The units of the region's co-ordinates."
    )
