# generated by datamodel-codegen:
#   filename:  datatypes/ImageLightType.json

from __future__ import annotations

from enum import Enum


class ImageLightType(Enum):
    """
    Type of light used e.g. for capturing an image
    """

    VISIBLE = "Visible"
    UV = "UV"
    OTHER = "other"
