# generated by datamodel-codegen:
#   filename:  datatypes/JobInputRole.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from enum import Enum


class JobInputRole(Enum):
    """
    Job input role, for the DB JobInputLink table
    """

    INPUT_DATA = "inputData"
    REFERENCE_DATA = "referenceData"
    TEMPLATE_DATA = "templateData"
