# generated by datamodel-codegen:
#   filename:  datatypes/JobStub.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field, RootModel


class MxlimsBaseType(RootModel[Literal["Job"]]):
    root: Literal["Job"] = Field(
        "Job",
        description="The type of the MXLIMS core object referred to. restricted in specific cases",
        title="MxlimsBaseType",
    )


class JobStub(BaseModel):
    """
    Uuid container, used for Uuid-only links to Jobs in messages
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mxlims_base_type: Literal["Job"] = Field(
        "Job",
        alias="mxlimsBaseType",
        description="The type of the MXLIMS core object referred to. restricted in specific cases",
        title="MxlimsBaseType",
    )
    uuid: UUID = Field(
        ...,
        description="Permanent unique identifier string of object referred to",
        title="Uuid",
    )
