# generated by datamodel-codegen:
#   filename:  datatypes/JobStatus.json

from __future__ import annotations

from enum import Enum


class JobStatus(Enum):
    """
    Job status enumeration
    """

    TEMPLATE = "Template"
    READY = "Ready"
    RUNNING = "Running"
    COMPLETED = "Completed"
    FAILED = "Failed"
    ABORTED = "Aborted"
