# generated by datamodel-codegen:
#   filename:  datatypes/PdbxSignalType.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from enum import Enum


class PdbxSignalType(Enum):
    """
    Observability criterion. Matches mmCIF item reflns.pdbx_signal_type

    https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_reflns.pdbx_signal_type.html)
    """

    LOCAL__I_SIGMA_I_ = "local <I/sigmaI>"
    LOCAL_W_CC_HALF = "local wCC_half"
