# generated by datamodel-codegen:
#   filename:  datatypes/Person.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Person(BaseModel):
    """
    Person
    """

    name: str = Field(..., description="The person's full name.")
    email_address: Optional[str] = Field(
        None, alias="emailAddress", description="The person's email address."
    )
    phone_number: Optional[str] = Field(
        None, alias="phoneNumber", description="The person's phone number."
    )
