# generated by datamodel-codegen:
#   filename:  datatypes/Person.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field


class Person(BaseModel):
    """
    Person
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="The person's full name.")
    email_address: str | None = Field(
        None, alias="emailAddress", description="The person's email address."
    )
    phone_number: str | None = Field(
        None, alias="phoneNumber", description="The person's phone number."
    )
