# generated by datamodel-codegen:
#   filename:  datatypes/PlateRegion.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field

from .Circle import Circle
from .Line import Line
from .PlateRegionUnit import PlateRegionUnit
from .Point import Point
from .Polygon import Polygon
from .Rectangle import Rectangle


class PlateRegion(BaseModel):
    """
    A region defined in absolute plate space.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    region: Point | Circle | Line | Rectangle | Polygon
    units: PlateRegionUnit = Field(
        ..., description="The units of the region's co-ordinates."
    )
