# generated by datamodel-codegen:
#   filename:  datatypes/PlateRegionUnit.json

from __future__ import annotations

from enum import Enum


class PlateRegionUnit(Enum):
    """
    Allowed units for plate region images
    """

    MM = "mm"
    MICRON = "micron"
