# generated by datamodel-codegen:
#   filename:  datatypes/PointCloud.json

from __future__ import annotations

from typing import List, Literal

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field


class Rectangle(BaseModel):
    """
    <A rectangular region marked on an image or in absolute plate space. The box is defined by two points on diagonally opposite corners, with its edges parallel to the X and Y axes. Ensure that the two X values are not equal, and that the two Y values are not equal.
    """

    volume_type: Literal["pointCloud"] = Field(
        "pointCloud",
        alias="volumeType",
        description="Type of volume representation",
        title="Volume Type",
    )
    points: List[List[float]] = Field(..., title="Points list")
