# generated by datamodel-codegen:
#   filename:  datatypes/PointCloud.json

from __future__ import annotations

from typing import List

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from .ScannedPoint import ScannedPoint


class PointCloud(BaseModel):
    """
    A cloud (list) of scanned points
    """

    points: List[ScannedPoint] = Field(
        ..., description="List of points making up the PointCloud", title="Points list"
    )
