# generated by datamodel-codegen:
#   filename:  datatypes/QualityFactorType.json

from __future__ import annotations

from enum import Enum


class QualityFactorType(Enum):
    """
    Name for quality factor type, used in QualityFactor class
    """

    R_MERGE_ = "R(merge)"
    R_MEAS_ = "R(meas)"
    R_PIM_ = "R(pim)"
    I_SIG_I = "I/SigI"
    CC_1_2_ = "CC(1/2)"
    CC_ANO_ = "CC(ano)"
    SIG_ANO = "SigAno"
    COMPLETENESS = "Completeness"
    COMPLETENESS_SPHERICAL = "CompletenessSpherical"
    COMPLETENESS_ELLIPSOIDAL = "CompletenessEllipsoidal"
    REDUNDANCY = "Redundancy"
    COMPLETENESS_ANO = "CompletenessAno"
    COMPLETENESS_ANO_SPHERICAL = "CompletenessAnoSpherical"
    COMPLETENESS_ANO_ELLIPSOIDAL = "CompletenessAnoEllipsoidal"
    REDUNDANCY_ANO = "RedundancyAno"
