# generated by datamodel-codegen:
#   filename:  datatypes/Rectangle.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, Field

from . import Point


class Rectangle(BaseModel):
    """
    <A rectangular region marked on an image or in absolute plate space. The box is defined by two points on diagonally opposite corners, with its edges parallel to the X and Y axes. Ensure that the two X values are not equal, and that the two Y values are not equal.
    """

    region_type: Literal["rectangle"] = Field(
        ..., alias="regionType", description="Type of region"
    )
    points: List[Point] = Field(..., max_length=2, min_length=2)
