# generated by datamodel-codegen:
#   filename:  datatypes/Region.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import Union

from pydantic import Field, RootModel

from . import Circle, Line, Point, Polygon, Rectangle


class Region(RootModel[Union[Point, Circle, Line, Rectangle, Polygon]]):
    root: Union[Point, Circle, Line, Rectangle, Polygon] = Field(
        ..., description="A region or point of interest.", title="Region"
    )
