# generated by datamodel-codegen:
#   filename:  datatypes/SampleComponentRole.json

from __future__ import annotations

from enum import Enum


class SampleComponentRole(Enum):
    """
    Role for SampleComponent. For crystallographic screening, 'target' is the macromolecule and 'ligand' is screened compound
    """

    TARGET = "target"
    LIGAND = "ligand"
    COFACTOR = "cofactor"
    SOLVENT = "solvent"
    BUFFER = "buffer"
    CRYOPROTECTANT = "cryoprotectant"
    OTHER = "other"
