# generated by datamodel-codegen:
#   filename:  datatypes/SampleComponent.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field, constr

from .SampleComponentRole import SampleComponentRole


class SampleComponent(BaseModel):
    """
    Component of Sample.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    acronym: str | None = Field(
        None,
        description="Acronym - short synonym of component (e.g. 'lig1'",
        title="Acronym",
    )
    name: str | None = Field(
        None, description="Human readable name of component", title="Name"
    )
    role: SampleComponentRole | None = None
    smiles: str | None = Field(
        None, description="Smile string defining component", title="Smiles"
    )
    selfies: str | None = Field(
        None, description="Selfies string defining component", title="Smiles"
    )
    sequence: str | None = Field(
        None, description="Sequence string defining component", title="Smiles"
    )
    identifiers: (
        dict[
            str,
            constr(
                pattern=r"^(?i)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
            ),
        ]
        | None
    ) = Field(
        None,
        description="Keyword-value dictionary string:string of site-specific object indentifiers. The key must be a valid domain name pointing to the site 'owning' the extensions, but need bw resovable.",
        title="Identifiers",
    )
    urls: (
        dict[
            str,
            constr(
                pattern=r"^(?i)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
            ),
        ]
        | None
    ) = Field(
        None,
        description="Keyword-value dictionary string:urlstring of site-specific object urls. The key must be a valid domain name pointing to the site 'owning' the extensions, but need bw resovable.",
        title="Urls",
    )
