# generated by datamodel-codegen:
#   filename:  datatypes/SampleStub.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import ConfigDict, Field


class SampleStub(BaseModel):
    """
    Uuid container, used for Uuid-only links to Samples in messages
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mxlims_base_type: Literal["Sample"] = Field(
        "Sample",
        alias="mxlimsBaseType",
        description="The type of the MXLIMS core object referred to",
        title="MxlimsBaseType",
    )
    uuid: UUID = Field(
        ...,
        description="Permanent unique identifier string of object referred to",
        title="Uuid",
    )
