# generated by datamodel-codegen:
#   filename:  datatypes/Scan.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class Scan(BaseModel):
    """
    Subdivision of CollectionSweep.

    The Scan describes a continuously acquired set of images that forms a subset of the
    CollectionSweep of which they form part. The ordinal gives the acquisition order of
    sweeps across an entire multi-sweep experiment; this allows you to describe
    out-of-order acquisition and interleaving.
    """

    scan_position_start: float = Field(
        ...,
        alias="scanPositionStart",
        description="Value of scan axis for the first image, in units matching axis type",
        title="Scan Position Start",
    )
    first_image_number: int = Field(
        ...,
        alias="firstImageNumber",
        description="Image number to use for first image",
        title="First Image Number",
    )
    number_images: conint(ge=0) = Field(
        ...,
        alias="numberImages",
        description="Number of images to acquire as part of the Scan.",
        title="Number Images",
    )
    ordinal: int = Field(
        ...,
        description="Ordinal defining the ordering of all scans within the experiment (not just within the scan)",
        title="Ordinal",
    )
