# generated by datamodel-codegen:
#   filename:  datatypes/Tensor.json

from __future__ import annotations

from typing import List

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field


class Tensor(BaseModel):
    """
    Tensor
    """

    eigenvalues: List = Field(
        ...,
        description="Eigenvalues of tensor",
        max_length=3,
        min_length=3,
        title="Eigenvalues",
    )
    eigenvectors: List[List] = Field(
        ...,
        description="Eigenvectors (unit vectors) of tensor, in same order as eigenvalues",
        title="Eigenvectors",
    )
