# generated by datamodel-codegen:
#   filename:  datatypes/TrackingDeviceType.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from enum import Enum


class TrackingDeviceType(Enum):
    """
    Type of tracking device for tracking samples, Dewars, etc.
    """

    LIGHT_BUG = "LightBug"
    AIR_TAG = "AirTag"
    OTHER = "other"
