# generated by mxlims/impl/generate_code.py
#  filename __init__.py

from mxlims.pydantic.messages.__init__ import __init__ as __init___orig
from mxlims.impl.pydantic.MxlimsBase import BaseMessage

class __init__(__init___orig, BaseMessage):
    """MxlimsMessage class, combining pydantic class with Implementation class"""
