# generated by mxlims/impl/generate_code.py
#  filename MxlimsMessageStrict.py

from mxlims.pydantic.messages.MxlimsMessageStrict import MxlimsMessageStrict as MxlimsMessageStrict_orig
from mxlims.impl.pydantic.MxlimsBase import BaseMessage

class MxlimsMessageStrict(MxlimsMessageStrict_orig, BaseMessage):
    """MxlimsMessage class, combining pydantic class with Implementation class"""
