# generated by datamodel-codegen:
#   filename:  data/MediumData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel


class MediumData(BaseModel):
    """
    Sample defining the medium (buffer, solvent,...) of another sample
    """
