# generated by datamodel-codegen:
#   filename:  data/MxProcessingData.json

from __future__ import annotations

from typing import Annotated

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import Field

from ..datatypes.Enumerations import SpaceGroupName
from ..datatypes.UnitCell import UnitCell


class MxProcessingData(BaseModel):
    """
    Crystallography Processing calculation,
    """

    program_name: Annotated[
        str | None,
        Field(
            alias="programName",
            description="Name of processing program",
            title="Program name",
        ),
    ] = None
    program_version: Annotated[
        str | None,
        Field(
            alias="programVersion",
            description="Version of processing program",
            title="Program version",
        ),
    ] = None
    space_group_name: Annotated[
        SpaceGroupName | None,
        Field(
            alias="spaceGroupName",
            description="Name of space group, to use for processing input. Names may include alternative settings. Matches mmCIF item symmetry.space_group_name_H-M (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_symmetry.space_group_name_H-M.html).",
            title="Space Group Name",
        ),
    ] = None
    unit_cell: Annotated[
        UnitCell | None,
        Field(
            alias="unitCell",
            description="Unit cell of crystal, to use for processing input.",
        ),
    ] = None
