# generated by datamodel-codegen:
#   filename:  data/PinPositionData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field, PositiveInt


class PinPositionData(BaseModel):
    """
    An independent Position within a Pin where crystals can be located.
    """

    position_in_pin: PositiveInt = Field(
        ...,
        alias="positionInPin",
        description="The pin position within  the pin. This should be validated against the pin's numberPositions property.",
        examples=[4],
    )
