# generated by datamodel-codegen:
#   filename:  data/PlateData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from ..datatypes.PlateType import PlateType
from ..datatypes.TrackingDevice import TrackingDevice


class PlateData(BaseModel):
    """
    A crystallization plate
    """

    barcode: str | None = Field(
        None, description="The plate barcode or other identifier"
    )
    plate_type: PlateType | None = Field(
        None, alias="plateType", description="Plate type description object"
    )
    tracking_device: TrackingDevice | None = Field(
        None, alias="trackingDevice", description="Plate tracking device"
    )
