# generated by datamodel-codegen:
#   filename:  data/WellDropData.json

from __future__ import annotations

from typing import Annotated

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import Field, PositiveInt


class WellDropData(BaseModel):
    """
    A drop in a well in a crystallization plate
    """

    drop_number: Annotated[
        PositiveInt,
        Field(
            alias="dropNumber",
            description="The drop number. This should be validated against the plateType's numberSubPositions property.",
        ),
    ]
