# generated by datamodel-codegen:
#   filename:  data/ReflectionSetData.json

from __future__ import annotations

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import Field

from ..datatypes.FooStats import FooStats as FooStats_1


class ReflectionSetData(BaseModel):
    foo_stats_overall: FooStats | None = Field(None, alias="fooStatsOverall")
    foo_stats_shells: list[FooStats_1] | None = Field(
        None, alias="fooStatsShells", title="Foo Stats Shells"
    )
