# generated by datamodel-codegen:
#   filename:  rawobjects/RawCrystallographicSample.json

from __future__ import annotations

from typing import Dict, List, Literal, Optional

from pydantic import Field, confloat

from ..core.PreparedSample import PreparedSample
from ..datatypes import SampleComponent, SpaceGroupName, UnitCell


class RawCrystallographicSample(PreparedSample):
    """
    Crystallographic Sample
    """

    mxlims_type: Literal["CrystallographicSample"] = Field(
        "CrystallographicSample",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="Mxlims Type",
    )
    macromolecule: Optional[SampleComponent] = Field(
        None, description="Macromolecule being studied - main component of the sample"
    )
    components: Optional[List[SampleComponent]] = Field(
        None, description="Other components of Sample", title="Sample components"
    )
    space_group_name: Optional[SpaceGroupName] = Field(
        None,
        alias="spaceGroupName",
        description="Name of expected space group, for processing. Names may include alternative settings. Matches mmCIF item symmetry.space_group_name_H-M (https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_symmetry.space_group_name_H-M.html).",
        title="Space Group Name",
    )
    unit_cell: Optional[UnitCell] = Field(
        None,
        alias="unitCell",
        description="Unit cell expected for crystals of this material",
    )
    radiation_sensitivity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        alias="radiationSensitivity",
        description="Relative radiation sensitivity of sample.",
        title="Radiation Sensitivity",
    )
    identifiers: Optional[Dict[str, str]] = Field(
        None,
        description="Dictionary str:str of contextName: identifier. ContextName will typically refer to a LIMS, database, or web site but could also be e.g. 'smiles' or 'sequence'",
        title="Identifiers",
    )
