# generated by datamodel-codegen:
#   filename:  rawobjects/RawDewar.json

from __future__ import annotations

from typing import Literal, Optional

from pydantic import Field

from ..core.LogisticalSample import LogisticalSample
from ..datatypes.TrackingDevice import TrackingDevice


class RawDewar(LogisticalSample):
    """
    A dewar containing pucks with mounted crystals on pins.
    """

    mxlims_type: Literal["Dewar"] = Field(
        "Dewar",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="Mxlims Type",
    )
    barcode: Optional[str] = Field(None, description="The dewar barcode or RFID code")
    tracking_device: Optional[TrackingDevice] = Field(None, alias="trackingDevice")
