# generated by datamodel-codegen:
#   filename:  rawobjects/RawMxProcessing.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import Literal, Optional

from pydantic import Field

from ..core.Job import Job
from ..datatypes import CrystalForm


class RawMxProcessing(Job):
    """
    Crystallography Processing calculation,
    """

    mxlims_type: Literal["MXProcessing"] = Field(
        "MXProcessing",
        alias="mxlimsType",
        description="Type of MXLIMS object.",
        title="Mxlims Type",
    )
    crystal_form: Optional[CrystalForm] = Field(
        None,
        alias="crystalForm",
        description="Crystal form, with unit cell and space group, to use for processing",
    )
