# generated by datamodel-codegen:
#   filename:  rawobjects/RawPlate.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import Dict, Literal, Optional

from pydantic import Field

from ..core.LogisticalSample import LogisticalSample
from ..datatypes import PlateType, TrackingDevice


class RawPlate(LogisticalSample):
    """
    A crystallization plate
    """

    mxlims_type: Literal["Plate"] = Field(
        "Plate",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="Mxlims Type",
    )
    barcode: Optional[str] = Field(
        None, description="The plate barcode or other identifier"
    )
    plate_type: Optional[PlateType] = Field(None, alias="plateType")
    identifiers: Optional[Dict[str, str]] = Field(
        None,
        description="Dictionary str:str of contextName: identifier. ContextName will typically refer to a LIMS, database, or web site but could also be e.g. 'smiles' or 'sequence'",
        title="Identifiers",
    )
    tracking_device: Optional[TrackingDevice] = Field(None, alias="trackingDevice")
