# generated by datamodel-codegen:
#   filename:  rawobjects/RawPinPosition.json

from __future__ import annotations

from typing import Literal

from pydantic import Field, conint

from ..core.LogisticalSample import LogisticalSample


class RawPinPosition(LogisticalSample):
    """
    An independent Position within a Pin where crystals can be located.
    """

    mxlims_type: Literal["PinPosition"] = Field(
        "PinPosition",
        alias="mxlimsType",
        description="The type of MXLIMS object.",
        title="Mxlims Type",
    )
    position_in_pin: conint(ge=1) = Field(
        ...,
        alias="positionInPin",
        description="The pin position within  the pin. This should be validated against the pin's numberPositions property.",
        examples=[4],
    )
