# generated by datamodel-codegen:
#   filename:  data/ReflectionSetData.json

from __future__ import annotations

from typing import List, Optional

from mxlims.impl.MxlimsBase import BaseModel
from pydantic import Field

from ..datatypes.FooStats import FooStats


class ReflectionSetData(BaseModel):
    foo_stats_overall: Optional[FooStats] = Field(None, alias="fooStatsOverall")
    foo_stats_shells: Optional[List[FooStats]] = Field(
        None, alias="fooStatsShells", title="Foo Stats Shells"
    )
