# generated by mxlims/impl/generate_code.py
#  filename mxlims_messages.py

""" MXLIMS message classes to use: Containing implementation + generated pydantic
"""
    
from mxlims.impl.MxlimsBase import BaseMessage

from mxlims.pydantic.messages.MxlimsMessage import MxlimsMessage as MxlimsMessage_orig
from mxlims.pydantic.messages.MxlimsMessageStrict import MxlimsMessageStrict as MxlimsMessageStrict_orig


class MxlimsMessage(MxlimsMessage_orig, BaseMessage):
    """MxlimsMessage class, combining pydantic class with Implementation class"""


class MxlimsMessageStrict(MxlimsMessageStrict_orig, BaseMessage):
    """MxlimsMessage class, combining pydantic class with Implementation class"""
