# generated by datamodel-codegen:
#   filename:  references/PlateRef.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field


class PlateRef(BaseModel):
    """
    Reference to Plate
    """

    mxlims_type: Literal["Plate"] = Field(
        "Plate",
        alias="mxlimsType",
        description="The type of the MXLIMS object referred to.",
        title="MxlimsType",
    )
    uuid: UUID = Field(
        ...,
        description="Permanent unique identifier string of referenced object",
        title="Uuid",
    )
