# generated by datamodel-codegen:
#   filename:  references/PuckRef.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import ConfigDict, Field


class PuckRef(BaseModel):
    """
    Reference to Puck
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mxlims_type: Literal["Puck"] = Field(
        "Puck",
        alias="mxlimsType",
        description="The type of the MXLIMS object referred to.",
        title="MxlimsType",
    )
    uuid: UUID = Field(
        ...,
        description="Permanent unique identifier string of referenced object",
        title="Uuid",
    )
