# generated by datamodel-codegen:
#   filename:  references/WellDropRef.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import ConfigDict, Field


class WellDropRef(BaseModel):
    """
    Reference to WellDrop
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mxlims_type: Literal["WellDrop"] = Field(
        "WellDrop",
        alias="mxlimsType",
        description="The type of the MXLIMS object referred to.",
        title="MxlimsType",
    )
    uuid: UUID = Field(
        ...,
        description="Permanent unique identifier string of referenced object",
        title="Uuid",
    )
