# generated by datamodel-codegen:
#   filename:  messages/BaseMessageData.json

from __future__ import annotations

from typing import Literal

from mxlims.impl.MxlimsBase import BaseMessage

from pydantic import Field


class BaseMessageData(BaseMessage):
    """
    Base data object for all MXLIMS messages
    """

    version: Literal["0.6.10"] = Field(
        "0.6.10", description="MXLIMS version for current model", title="Version"
    )
