# generated by datamodel-codegen:
#   filename:  messages/JobMessage.json

from __future__ import annotations

from typing import Union

from mxlims.pydantic.MxBaseModel import BaseModel

from ..data.CrystallographicSample import CrystallographicSample
from ..logical_model.MxExperiment import MxExperiment
from ..logical_model.MxProcessing import MxProcessing


class JobMessage(BaseModel):
    """
    Message used for a single job with contents and the associated (raw) PreparedSample.
    """

    job: Union[MxExperiment, MxProcessing]
    sample: CrystallographicSample


JobMessage.model_rebuild()
