# generated by datamodel-codegen:
#   filename:  messages/MxlimsMessage.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import ConfigDict, Field

from ..datatypes.DatasetStub import DatasetStub
from ..datatypes.JobStub import JobStub
from ..datatypes.LogisticalSampleStub import LogisticalSampleStub
from ..datatypes.SampleStub import SampleStub
from .MxlimsMessageStrict import MxlimsMessageStrict


class MxlimsMessage(MxlimsMessageStrict):
    """
    Message containing all possible objects, by type
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dataset: Optional[Dict[str, DatasetStub]] = Field(
        None,
        alias="Dataset",
        description="idString:object dictionary of Dataset stubs.",
        title="Datasets",
    )
    job: Optional[Dict[str, JobStub]] = Field(
        None,
        alias="Job",
        description="idString:object dictionary of Job stubs.",
        title="Jobs",
    )
    logistical_sample: Optional[Dict[str, LogisticalSampleStub]] = Field(
        None,
        alias="LogisticalSample",
        description="idString:object dictionary of LogisticalSample stubs.",
        title="LogisticalSamples",
    )
    sample: Optional[Dict[str, SampleStub]] = Field(
        None,
        alias="Sample",
        description="idString:object dictionary of Sample stubs.",
        title="Samples",
    )
