# generated by datamodel-codegen:
#   filename:  messages/MxlimsMessageStrict.json

from __future__ import annotations

from typing import Dict, Optional

from mxlims.impl.MxlimsBase import BaseModel

from pydantic import Field

from ..objects.CollectionSweep import CollectionSweep
from ..objects.Crystal import Crystal
from ..objects.Dewar import Dewar
from ..objects.DropRegion import DropRegion
from ..objects.Macromolecule import Macromolecule
from ..objects.MacromoleculeSample import MacromoleculeSample
from ..objects.Medium import Medium
from ..objects.MultiPin import MultiPin
from ..objects.MxExperiment import MxExperiment
from ..objects.MxProcessing import MxProcessing
from ..objects.Pin import Pin
from ..objects.PinPosition import PinPosition
from ..objects.Plate import Plate
from ..objects.PlateWell import PlateWell
from ..objects.Puck import Puck
from ..objects.ReflectionSet import ReflectionSet
from ..objects.Shipment import Shipment
from ..objects.WellDrop import WellDrop


class MxlimsMessageStrict(BaseModel):
    """
    Message containing all possible objects, by type
    """

    collection_sweep: Optional[Dict[str, CollectionSweep]] = Field(
        None,
        alias="CollectionSweep",
        description="idString:object dictionary of CollectionSweeps.",
        title="CollectionSweeps",
    )
    crystal: Optional[Dict[str, Crystal]] = Field(
        None,
        alias="Crystal",
        description="idString:object dictionary of Crystals.",
        title="Crystals",
    )
    dewar: Optional[Dict[str, Dewar]] = Field(
        None,
        alias="Dewar",
        description="idString:object dictionary of Dewars.",
        title="Dewars",
    )
    drop_region: Optional[Dict[str, DropRegion]] = Field(
        None,
        alias="DropRegion",
        description="idString:object dictionary of DropRegions.",
        title="DropRegions",
    )
    macromolecule: Optional[Dict[str, Macromolecule]] = Field(
        None,
        alias="Macromolecule",
        description="idString:object dictionary of Macromolecule (reference sample) objects.",
        title="Macromolecule",
    )
    macromolecule_sample: Optional[Dict[str, MacromoleculeSample]] = Field(
        None,
        alias="MacromoleculeSample",
        description="idString:object dictionary of Macromolecule-containing sample objects.",
        title="MacromoleculeSample",
    )
    medium: Optional[Dict[str, Medium]] = Field(
        None,
        alias="Medium",
        description="idString:object dictionary of Medium (sample) objects.",
        title="Media",
    )
    mx_experiment: Optional[Dict[str, MxExperiment]] = Field(
        None,
        alias="MxExperiment",
        description="idString:object dictionary of MxExperiments.",
        title="MxExperiments",
    )
    mx_processing: Optional[Dict[str, MxProcessing]] = Field(
        None,
        alias="MxProcessing",
        description="idString:object dictionary of MxProcessings.",
        title="MxProcessings",
    )
    multi_pin: Optional[Dict[str, MultiPin]] = Field(
        None,
        alias="MultiPin",
        description="idString:object dictionary of MultiPins.",
        title="MultiPins",
    )
    pin: Optional[Dict[str, Pin]] = Field(
        None,
        alias="Pin",
        description="idString:object dictionary of Pins.",
        title="Pins",
    )
    pin_position: Optional[Dict[str, PinPosition]] = Field(
        None,
        alias="PinPosition",
        description="idString:object dictionary of PinPositions.",
        title="PinPositions",
    )
    plate: Optional[Dict[str, Plate]] = Field(
        None,
        alias="Plate",
        description="idString:object dictionary of Plates.",
        title="Plates",
    )
    plate_well: Optional[Dict[str, PlateWell]] = Field(
        None,
        alias="PlateWell",
        description="idString:object dictionary of PlateWells.",
        title="PlateWells",
    )
    puck: Optional[Dict[str, Puck]] = Field(
        None,
        alias="Puck",
        description="idString:object dictionary of Pucks.",
        title="Pucks",
    )
    reflection_set: Optional[Dict[str, ReflectionSet]] = Field(
        None,
        alias="ReflectionSet",
        description="idString:object dictionary of ReflectionSets.",
        title="ReflectionSets",
    )
    shipment: Optional[Dict[str, Shipment]] = Field(
        None,
        alias="Shipment",
        description="idString:object dictionary of Shipments.",
        title="Shipments",
    )
    well_drop: Optional[Dict[str, WellDrop]] = Field(
        None,
        alias="WellDrop",
        description="idString:object dictionary of WellDrops.",
        title="WellDrops",
    )
