# generated by datamodel-codegen:
#   filename:  messages/SamplesMessage.json

from __future__ import annotations

from typing import List

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field

from ..logical_model.CrystallographicSample import CrystallographicSample


class SamplesMessage(BaseModel):
    """
    Message containing Samples together with their content links
    """

    samples: List[CrystallographicSample] = Field(..., min_length=1)
