# generated by datamodel-codegen:
#   filename:  messages/ShipmentMessage.json

from __future__ import annotations

from typing import List, Union

from mxlims.pydantic.MxBaseModel import BaseModel

from pydantic import Field

from ..data.CrystallographicSample import CrystallographicSample
from ..logical_model.DewarShipment import DewarShipment
from ..logical_model.PlateShipment import PlateShipment


class ShipmentMessage(BaseModel):
    """
    Message used for shipments. Samples have no content links and must be linked using preparedSampleId
    """

    shipment: Union[DewarShipment, PlateShipment]
    samples: List[CrystallographicSample] = Field(..., min_length=1)
