# generated by datamodel-codegen:
#   filename:  messages/ShipmentMessage.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import Field

from .MxlimsMessageStrict import MxlimsMessageStrict


class ShipmentMessage(MxlimsMessageStrict):
    """
    Message containing a shipment of either frozen crystals or crystallization plates
    """

    shipment: Any = Field(..., alias="Shipment")
    plate: Optional[Any] = Field(None, alias="Plate")
    plate_well: Optional[Any] = Field(None, alias="PlateWell")
    well_drop: Optional[Any] = Field(None, alias="WellDrop")
    drop_region: Optional[Any] = Field(None, alias="DropRegion")
    dewar: Optional[Any] = Field(None, alias="Dewar")
    puck: Optional[Any] = Field(None, alias="Puck")
    multi_pin: Optional[Any] = Field(None, alias="MultiPin")
    pin: Optional[Any] = Field(None, alias="Pin")
    pin_position: Optional[Any] = Field(None, alias="PinPosition")
    macromolecule_sample: Any = Field(..., alias="MacromoleculeSample")
    macromolecule: Any = Field(..., alias="Macromolecule")
    crystal: Optional[Any] = Field(None, alias="Crystal")
