# generated by datamodel-codegen:
#   filename:  messages/ShipmentMessage.json
#   timestamp: 2025-03-23T15:25:48+00:00

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from ..objects import DewarShipment, PlateShipment
from ..rawobjects import RawCrystallographicSample


class ShipmentMessage(BaseModel):
    """
    Message used for shipments. Samples have no content links and must be linked using preparedSampleId
    """

    shipment: Union[DewarShipment, PlateShipment]
    samples: List[RawCrystallographicSample] = Field(..., min_length=1)
